### ISSUE TITLE
FE: React head tag issue

### ISSUE THREAD

**Issue by TamahauBrown** [TamahauBrown/poker-trainer#8]
React does not accept head tags inside of divs but this is the only way we currently have to import noto sans.

Console Error:
The following console error is that the console is unhappy with the head tag.
![image](https://user-images.githubusercontent.com/48704237/189518308-c4963fb4-d355-4b16-bc51-a250d1787e99.png)

Code it is referring to:
Can be found in the App.tsx file here:
![image](https://user-images.githubusercontent.com/48704237/189518328-78613b78-100a-4280-b20f-bcf19b14ae20.png)

Proposed solution:
Peer programming on potential alternative solutions

**Comment by 8176135** [comment]
Try removing the <head> and </head>, just have the link part directly.

**Comment by TamahauBrown** [comment]
Ok, that holds. Closing issue
